list: $/nambit/staff/models/entry/columns.yaml
modelClass: Nambit\Staff\Models\Entry
title: Entries
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'nambit/staff/entries/update/:id'
